// Constants untuk dropdown options

export const PROVINSI_INDONESIA = [
  { id: 'aceh', nama: 'Aceh' },
  { id: 'sumatera-utara', nama: 'Sumatera Utara' },
  { id: 'sumatera-barat', nama: 'Sumatera Barat' },
  { id: 'riau', nama: 'Riau' },
  { id: 'kepulauan-riau', nama: 'Kepulauan Riau' },
  { id: 'jambi', nama: 'Jambi' },
  { id: 'sumatera-selatan', nama: 'Sumatera Selatan' },
  { id: 'bangka-belitung', nama: 'Bangka Belitung' },
  { id: 'bengkulu', nama: 'Bengkulu' },
  { id: 'lampung', nama: 'Lampung' },
  { id: 'dki-jakarta', nama: 'DKI Jakarta' },
  { id: 'jawa-barat', nama: 'Jawa Barat' },
  { id: 'banten', nama: 'Banten' },
  { id: 'jawa-tengah', nama: 'Jawa Tengah' },
  { id: 'di-yogyakarta', nama: 'DI Yogyakarta' },
  { id: 'jawa-timur', nama: 'Jawa Timur' },
  { id: 'bali', nama: 'Bali' },
  { id: 'nusa-tenggara-barat', nama: 'Nusa Tenggara Barat' },
  { id: 'nusa-tenggara-timur', nama: 'Nusa Tenggara Timur' },
  { id: 'kalimantan-barat', nama: 'Kalimantan Barat' },
  { id: 'kalimantan-tengah', nama: 'Kalimantan Tengah' },
  { id: 'kalimantan-selatan', nama: 'Kalimantan Selatan' },
  { id: 'kalimantan-timur', nama: 'Kalimantan Timur' },
  { id: 'kalimantan-utara', nama: 'Kalimantan Utara' },
  { id: 'sulawesi-utara', nama: 'Sulawesi Utara' },
  { id: 'gorontalo', nama: 'Gorontalo' },
  { id: 'sulawesi-tengah', nama: 'Sulawesi Tengah' },
  { id: 'sulawesi-barat', nama: 'Sulawesi Barat' },
  { id: 'sulawesi-selatan', nama: 'Sulawesi Selatan' },
  { id: 'sulawesi-tenggara', nama: 'Sulawesi Tenggara' },
  { id: 'maluku', nama: 'Maluku' },
  { id: 'maluku-utara', nama: 'Maluku Utara' },
  { id: 'papua', nama: 'Papua' },
  { id: 'papua-barat', nama: 'Papua Barat' },
  { id: 'papua-tengah', nama: 'Papua Tengah' },
  { id: 'papua-pegunungan', nama: 'Papua Pegunungan' },
  { id: 'papua-selatan', nama: 'Papua Selatan' },
  { id: 'papua-barat-daya', nama: 'Papua Barat Daya' },
]

export const KOTA_BY_PROVINSI: Record<string, { id: string; nama: string }[]> = {
  'dki-jakarta': [
    { id: 'jakarta-pusat', nama: 'Jakarta Pusat' },
    { id: 'jakarta-utara', nama: 'Jakarta Utara' },
    { id: 'jakarta-barat', nama: 'Jakarta Barat' },
    { id: 'jakarta-selatan', nama: 'Jakarta Selatan' },
    { id: 'jakarta-timur', nama: 'Jakarta Timur' },
    { id: 'kepulauan-seribu', nama: 'Kepulauan Seribu' },
  ],
  'jawa-barat': [
    { id: 'bandung', nama: 'Kota Bandung' },
    { id: 'bandung-barat', nama: 'Kabupaten Bandung Barat' },
    { id: 'bandung-kab', nama: 'Kabupaten Bandung' },
    { id: 'bekasi', nama: 'Kota Bekasi' },
    { id: 'bekasi-kab', nama: 'Kabupaten Bekasi' },
    { id: 'bogor', nama: 'Kota Bogor' },
    { id: 'bogor-kab', nama: 'Kabupaten Bogor' },
    { id: 'cimahi', nama: 'Kota Cimahi' },
    { id: 'cirebon', nama: 'Kota Cirebon' },
    { id: 'cirebon-kab', nama: 'Kabupaten Cirebon' },
    { id: 'depok', nama: 'Kota Depok' },
    { id: 'garut', nama: 'Kabupaten Garut' },
    { id: 'indramayu', nama: 'Kabupaten Indramayu' },
    { id: 'karawang', nama: 'Kabupaten Karawang' },
    { id: 'kuningan', nama: 'Kabupaten Kuningan' },
    { id: 'majalengka', nama: 'Kabupaten Majalengka' },
    { id: 'pangandaran', nama: 'Kabupaten Pangandaran' },
    { id: 'purwakarta', nama: 'Kabupaten Purwakarta' },
    { id: 'subang', nama: 'Kabupaten Subang' },
    { id: 'sukabumi', nama: 'Kota Sukabumi' },
    { id: 'sukabumi-kab', nama: 'Kabupaten Sukabumi' },
    { id: 'sumedang', nama: 'Kabupaten Sumedang' },
    { id: 'tasikmalaya', nama: 'Kota Tasikmalaya' },
    { id: 'tasikmalaya-kab', nama: 'Kabupaten Tasikmalaya' },
  ],
  'banten': [
    { id: 'tangerang', nama: 'Kota Tangerang' },
    { id: 'tangerang-selatan', nama: 'Kota Tangerang Selatan' },
    { id: 'tangerang-kab', nama: 'Kabupaten Tangerang' },
    { id: 'serang', nama: 'Kota Serang' },
    { id: 'serang-kab', nama: 'Kabupaten Serang' },
    { id: 'cilegon', nama: 'Kota Cilegon' },
    { id: 'lebak', nama: 'Kabupaten Lebak' },
    { id: 'pandeglang', nama: 'Kabupaten Pandeglang' },
  ],
  'jawa-tengah': [
    { id: 'semarang', nama: 'Kota Semarang' },
    { id: 'semarang-kab', nama: 'Kabupaten Semarang' },
    { id: 'solo', nama: 'Kota Surakarta (Solo)' },
    { id: 'magelang', nama: 'Kota Magelang' },
    { id: 'magelang-kab', nama: 'Kabupaten Magelang' },
    { id: 'salatiga', nama: 'Kota Salatiga' },
    { id: 'pekalongan', nama: 'Kota Pekalongan' },
    { id: 'tegal', nama: 'Kota Tegal' },
    { id: 'banyumas', nama: 'Kabupaten Banyumas' },
    { id: 'cilacap', nama: 'Kabupaten Cilacap' },
    { id: 'purwokerto', nama: 'Purwokerto' },
  ],
  'di-yogyakarta': [
    { id: 'yogyakarta', nama: 'Kota Yogyakarta' },
    { id: 'sleman', nama: 'Kabupaten Sleman' },
    { id: 'bantul', nama: 'Kabupaten Bantul' },
    { id: 'kulon-progo', nama: 'Kabupaten Kulon Progo' },
    { id: 'gunung-kidul', nama: 'Kabupaten Gunung Kidul' },
  ],
  'jawa-timur': [
    { id: 'surabaya', nama: 'Kota Surabaya' },
    { id: 'malang', nama: 'Kota Malang' },
    { id: 'malang-kab', nama: 'Kabupaten Malang' },
    { id: 'batu', nama: 'Kota Batu' },
    { id: 'kediri', nama: 'Kota Kediri' },
    { id: 'blitar', nama: 'Kota Blitar' },
    { id: 'mojokerto', nama: 'Kota Mojokerto' },
    { id: 'madiun', nama: 'Kota Madiun' },
    { id: 'pasuruan', nama: 'Kota Pasuruan' },
    { id: 'probolinggo', nama: 'Kota Probolinggo' },
    { id: 'sidoarjo', nama: 'Kabupaten Sidoarjo' },
    { id: 'gresik', nama: 'Kabupaten Gresik' },
    { id: 'jember', nama: 'Kabupaten Jember' },
  ],
  'bali': [
    { id: 'denpasar', nama: 'Kota Denpasar' },
    { id: 'badung', nama: 'Kabupaten Badung' },
    { id: 'gianyar', nama: 'Kabupaten Gianyar' },
    { id: 'tabanan', nama: 'Kabupaten Tabanan' },
    { id: 'buleleng', nama: 'Kabupaten Buleleng' },
    { id: 'karangasem', nama: 'Kabupaten Karangasem' },
    { id: 'klungkung', nama: 'Kabupaten Klungkung' },
    { id: 'bangli', nama: 'Kabupaten Bangli' },
    { id: 'jembrana', nama: 'Kabupaten Jembrana' },
  ],
}

export const REGION_CLUSTERS = [
  'Jabodetabek',
  'Joglosemar',
  'Jawa Barat',
  'Jawa Timur',
  'Bali-Lombok',
  'Sumatera',
  'Kalimantan',
  'Sulawesi',
  'Papua & Maluku',
  'Virtual/Online',
]

export const ZONA_WAKTU = ['WIB', 'WITA', 'WIT']

export const TIPE_EVENT = [
  'Road Run',
  'Trail Run',
  'Charity Run',
  'Fun Run',
  'Virtual Run',
]

export const KATEGORI_JARAK = [
  '5K',
  '5-10km',
  '10K',
  '11-21km',
  'HM',
  '22-42km',
  'FM',
  'Ultra',
]

export const LABEL_SERTIFIKASI = [
  'WA Elite',
  'WA Gold',
  'WA',
  'AIMS',
  'WMM',
  'PASI',
  'ARRS',
  'ITRA',
  'UTMB',
]

export const FASILITAS_STANDARD = [
  'Jersey',
  'Finisher Tee',
  'Medali',
  'Refreshment',
  'Bib (Nomor Dada)',
]

export const STATUS_PENYELENGGARAAN = [
  { value: 'normal', label: 'Normal' },
  { value: 'diundur', label: 'Diundur' },
  { value: 'dibatalkan', label: 'Dibatalkan' },
]
